#include<MKL25Z4.h>
#include<stdbool.h>
#include "adc.h"

#define ADC_SHIFT 30

enum CFG1_ADICLK { BUS_CLOCK, BUS_CLOCK_DIV_2, ALTERNATE_CLOCK, ADC_ASYNC_CLOCK};
enum CFG1_ADIV { CLK_DIV_1, CLK_DIV_2, CLK_DIV_4, CLK_DIV_8};
enum CFG1_ADLPC { HIGH_POWER_MODE, LOW_POWER_MODE};
enum CFG1_ADLSMP { SHORT_SAMPLE_TIME, LONG_SAMPLE_TIME};
enum CFG1_MODE { ADC_RESULT_8b, ADC_RESULT_12b, ADC_RESULT_10b, ADC_RESULT_16b };
enum ADC_SC2_REFSEL {VREF, VALT};
enum ADC_SC2_ADTRG { SOFTWARE_TRIGGER, HARDWARE_TRIGGER };
enum ADC_SC3_ADCO { CONTINUOUS_CONVERSION_DISABLE,CONTINUOUS_CONVERSION_ENABLE};
enum ADC_SC1_DIFF {SINGLE_ENDED_INPUT, DIFFERENTIAL_INPUT};
enum ADC_SC1_AIEN { IRQ_DISABLE, IRQ_ENABLE};

void initialize_adc()
{
	SIM->SCGC6 |= SIM_SCGC6_ADC0_MASK;
	SIM->SCGC5 |= SIM_SCGC5_PORTE_MASK;

	PORTE->PCR[ADC_SHIFT] &= ~PORT_PCR_MUX_MASK;
	PORTE->PCR[ADC_SHIFT] |= PORT_PCR_MUX(0);

	ADC0->CFG1 = ADC_CFG1_ADICLK(BUS_CLOCK_DIV_2) | ADC_CFG1_ADIV(CLK_DIV_2) | ADC_CFG1_ADLPC(HIGH_POWER_MODE) | ADC_CFG1_ADLSMP( SHORT_SAMPLE_TIME) | ADC_CFG1_MODE(ADC_RESULT_16b);

	ADC0->SC2 = ADC_SC2_REFSEL(VALT) | ADC_SC2_ADTRG(SOFTWARE_TRIGGER);
	ADC0->SC3 = ADC_SC3_ADCO (CONTINUOUS_CONVERSION_DISABLE);

	adc_start_conversion();
}

void adc_start_conversion()
{
	ADC0-> SC1[0] = ADC_SC1_DIFF(SINGLE_ENDED_INPUT) | ADC_SC1_AIEN(IRQ_DISABLE) | ADC_SC1_ADCH(0);
}

_Bool adc_input_is_ready()
{
	return ADC0->SC1[0]  & ADC_SC1_COCO_MASK;
}

unsigned adc_get_input()
{
	return ADC0->R[0];
}
