#include <MKL25Z4.h>
#include "dac0.h"

#define DAC0_SHIFT 30

#define PCR_MUX_ANALOG 0

enum DAC_BUFFER_WORK_MODE {NORMAL_MODE=0, ONE_TIME_SCAN=1};
enum DAC_DACRFS_CHOICES { VREFH=0, VDDA=1};
enum DAC_TRIGGERS {HARDWARE=0, SOFTWARE=1};
enum DAC_POWER_MODES {LOW_POWER_MODE=0, HIGH_POWER_MODE=1};

#define DAC_BUFSIZE 2

void initialize_dac0()
{
	SIM->SCGC6 |= SIM_SCGC6_DAC0_MASK;
	SIM->SCGC5 |= SIM_SCGC5_PORTE_MASK;

	PORTE->PCR[DAC0_SHIFT] = (PORTE->PCR[DAC0_SHIFT] & ~PORT_PCR_MUX_MASK) | PORT_PCR_MUX(PCR_MUX_ANALOG);

	DAC0->C1 = DAC_C1_DMAEN(0) | DAC_C1_DACBFMD(NORMAL_MODE) | DAC_C1_DACBFEN(1);

	BUFDAC0 ->C2 = DAC_C2_DACBFRP(0) | DAC_C2_DACBUFUP( DAC_BUFSIZE -1 );

	DAC0->C0 = DAC_C0_DACEN(1) | DAC_C0_REFS (VDDA) | DAC_C0_DACTRGSEL(SOFTWARE) | DAC_C0_LPEN(HIGH_POWER_MODE) | DAC_C0_DACBTIEN(0) | DAC_C0_DACBBIEN(0);
}

void dac0_write_next_voltage(unsigned voltage)
{
	DAC0-> DAT[0].DATL = DAC_DATL_DATA0(voltage);
	DAC0-> DAT[0].DATH = DAC_DATH_DATA1(voltage >> 8);
}

void dac0_update_voltage()
{
	DAC0->C0 |= DAC_C0_DACSWTRG_MASK;
}
